### ISSUE TITLE
Getting error "Error: helm-charts chart not found in repo https://nerdswords.github.io/helm-charts"

### ISSUE THREAD

**Issue by tarvez05** [nerdswords/helm-charts#16]
Executed "helm repo add nerdswords https://nerdswords.github.io/helm-charts" 
then executing " helm dependency update ."

getting error :- Error: helm-charts chart not found in repo https://nerdswords.github.io/helm-charts

Can anyone please help

**Comment by cristiangreco** [comment]
@tarvez05 did you manage to solve this problem?

**Comment by cristiangreco** [comment]
Closing due to staleness, feel free to re-open in case you need any further help.
