### ISSUE TITLE
Publish charts as OCI artifact

### ISSUE THREAD

**Issue by jkroepke** [nerdswords/helm-charts#46]
Please publish the helm charts as OCI artifact. Helm support it natively and the avoid a separate repo management on the client level.

The OCI push could be easily attach to the `helm/chart-releaser-action` action.

Example: 

https://github.com/prometheus-community/helm-charts/blob/b4001815202cc773a51ad9b9de5a56eca18660d6/.github/workflows/release.yaml#L45-L61

**Comment by cristiangreco** [comment]
Done in https://github.com/nerdswords/helm-charts/pull/48
