### ISSUE TITLE
Adding support for automountServiceAccountToken to serviceaccount.yaml template

### ISSUE THREAD

**Issue by elijah** [nerdswords/helm-charts#54]
I needed to add this to quiet a Kyverno warning in one of our YACE deployments - figured that pushing the work upstream was a good idea.

Any suggestions you have for how this should be supported in the YACE helm chart, i'd be happy to take a stab at implementing.

I initially had an "if" block wrapped around the automountServiceAccountTokens: statement in the template, but one of my coworkers pointed out that the default in k8s seems to often by true - so the if block would make more sense if we just overrode the default with "false" to get the behavior that we want.

**Comment by cristiangreco** [comment]
Thanks for your contribution in https://github.com/nerdswords/helm-charts/pull/53

This will be released with chart version `0.33.0`
